Security API for CCP: User Class Reference
User Class Reference
User class.
#include <user.hpp>
Public Member Functions
User (const char login[MAX_LOGIN_LEN], uint32_t id, role_t role)
This constructor create a user from a login, id and role.
~User ()
User destructor.
myerror_t dump (uint8_t **pointer, size_t *size) const
This function serialize the User class into an array of bytes.
const char * getLogin () const
Function returning the login of the user.
Static Public Member Functions
static myerror_t parse (uint8_t *buffer, User **res)
This function parse a buffer to create a User class.
Data Fields
const uint32_t id
Id of the user, must be unique.
const role_t role
Role of the user.
Static Public Attributes
static constexpr size_t dumpSize = MAX_LOGIN_LEN + 5
Size of the class once dumped into a byte array.
Private Attributes
char login [MAX_LOGIN_LEN+1]
Login of the user.
Detailed Description
Definition at line 30 of file user.hpp.
Constructor & Destructor Documentation
User::User (const char login[MAX_LOGIN_LEN], uint32_t id, role_t role)
Definition at line 5 of file user.cpp.
References login.
Referenced by parse().
User::~User ()
Definition at line 11 of file user.cpp.
Member Function Documentation
myerror_t User::dump (uint8_t ** pointer, size_t * size) const
This function is for example used to dump a User class when saving the API in a file.
Parameters
pointer is a pointer to the buffer that will contain the result. *pointer should be initialised to NULL since the memory allocation will be done by the function.
size is a pointer to an integer that which value will be set to the actual size of the allocated buffer.
Returns
NO_ERROR if no error occured
ERROR_PARAM if pointer is NULL or *pointer is not NULL
Definition at line 15 of file user.cpp.
References dumpSize, ERROR_PARAM, login, MAX_LOGIN_LEN, NO_ERROR, and role.
const char * User::getLogin () const
Definition at line 58 of file user.cpp.
References login.
Referenced by API::addUser().
myerror_t User::parse (uint8_t * buffer, User ** res) static
This function is for example used to construct User classes when loading the API from a file.
Parameters
buffer is the byte array from which data will be read.
res is a pointer to the User pointer that will contain the result. *pointer should be initialised to NULL since the memory allocation will be done by the function.
Returns
NO_ERROR if no error occured
ERROR_PARAM if res is NULL or *res is not NULL
Definition at line 34 of file user.cpp.
References ERROR_MEM, ERROR_PARAM, id, login, NO_ERROR, role, and User().
Referenced by API::loadAPI().
Field Documentation
char User::login[MAX_LOGIN_LEN+1] private
The size of a login is at most MAX_LOGIN_LEN.
Definition at line 89 of file user.hpp.
Referenced by dump(), getLogin(), parse(), and User().
The documentation for this class was generated from the following files:
includes/user.hpp
src/user.cpp