Security API for CCP: AES Class Reference
AES Class Reference
AES class.
#include <aes.hpp>
Static Public Member Functions
static void encrypt (const uint8_t key[16], const uint8_t plaintext[16], uint8_t ciphertext[16])
Function used to encrypt a plaintext into a ciphertext using AES.
static void decrypt (const uint8_t key[16], const uint8_t ciphertext[16], uint8_t plaintext[16])
Function used to decrypt a ciphertext into a plaintext using AES.
static myerror_t test ()
Auto test function to test AES implementation w.r. to few test vectors (from NIST).
Static Private Member Functions
static void keySchedule (const uint8_t key[16], uint32_t subkeys[44])
AES-128 key schedule function for encryption.
static void keySchedule_inv (const uint8_t key[16], uint32_t subkeys[44])
AES-128 key schedule function for decryption.
static void round (const uint32_t subkey[4], uint32_t state[4])
AES round function based on big tables.
static void round_inv (const uint32_t subkey[4], uint32_t state[4])
AES inverse round function based on big tables.
Static Private Attributes
static const uint32_t Te0 [256]
Big table 0 for encryption: line 0.
static const uint32_t Te1 [256]
Big table 1 for encryption: line 1.
static const uint32_t Te2 [256]
Big table 2 for encryption: line 2.
static const uint32_t Te3 [256]
Big table 3 for encryption: line 3.
static const uint32_t Te4 [256]
Big table 4 for encryption: used in last round and key schedule.
static const uint32_t Td0 [256]
Big table 0 for decryption: line 0.
static const uint32_t Td1 [256]
Big table 1 for decryption: line 1.
static const uint32_t Td2 [256]
Big table 2 for decryption: line 2.
static const uint32_t Td3 [256]
Big table 3 for decryption: line 3.
static const uint32_t Td4 [256]
Big table 4 for decryption: used in last round and key schedule.
static const uint32_t rcon [10]
Round constants for key schedule.
static const uint8_t TV_keys [2][16]
Keys used in test vectors.
static const uint8_t TV_plaintexts [2][16]
Plaintexts used in test vectors.
static const uint8_t TV_ciphertexts [2][16]
Ciphertexts used in test vectors.
Detailed Description
Definition at line 14 of file aes.hpp.
Member Function Documentation
void AES::decrypt (const uint8_t key[16], const uint8_t ciphertext[16], uint8_t plaintext[16]) static
This function decrypts the provided ciphertext using the given key in AES-128.
Parameters
key is a 16-byte long array containing the key.
ciphertext is a 16-byte long array containing the ciphertext to decrypt.
plaintext is a pointer to a 16-byte long array that will contain the decrypted message.
Key Schedule call
Conversion of plaintext from bytes to 32-bit words
Last key xor
9 plain rounds
Partial round
First addRoundKey
Conversion of state from 32-bit words to bytes
Definition at line 90 of file aes.cpp.
References keySchedule_inv(), round(), round_inv(), and Td4.
Referenced by test().
void AES::encrypt (const uint8_t key[16], const uint8_t plaintext[16], uint8_t ciphertext[16]) static
This function encrypts the provided plaintext using the given key in AES-128.
Parameters
key is a 16-byte long array containing the key.
plaintext is a 16-byte long array containing the plaintext to encrypt.
ciphertext is a pointer to a 16-byte long array that will contain the encrypted message.
Key Schedule call
Conversion of plaintext from bytes to 32-bit words
First addRoundKey
9 plain rounds
Last round
Conversion of state from 32-bit words to bytes
Definition at line 41 of file aes.cpp.
References keySchedule(), round(), and Te4.
Referenced by test().
void AES::keySchedule (const uint8_t key[16], uint32_t subkeys[44]) static private
Conversion from bytes to 32-bit words
Key schedule
Definition at line 175 of file aes.cpp.
References rcon, and Te4.
Referenced by encrypt(), and keySchedule_inv().
void AES::keySchedule_inv (const uint8_t key[16], uint32_t subkeys[44]) static private
Expand keys
Invert order
Apply inverse MixColumn
Definition at line 208 of file aes.cpp.
References keySchedule(), Td0, Td1, Td2, Td3, and Te4.
Referenced by decrypt().
myerror_t AES::test () static
This function uses test vectors defined in the class and test implementation versus them.
Returns
ERROR_UNEXPECTED if a mismatch is found
NO_ERROR if everything matches
Testing encryption
Testing decryption
Definition at line 5 of file aes.cpp.
References decrypt(), encrypt(), ERROR_UNEXPECTED, NO_ERROR, TV_ciphertexts, TV_keys, and TV_plaintexts.
Field Documentation
const uint32_t AES::rcon static private
Initial value:
= {
    0x01000000, 0x02000000, 0x04000000, 0x08000000,
    0x10000000, 0x20000000, 0x40000000, 0x80000000,
    0x1B000000, 0x36000000,
}
Definition at line 87 of file aes.hpp.
Referenced by keySchedule().
const uint8_t AES::TV_ciphertexts static private
Initial value:
= {
  {0x3a,0xd7,0x7b,0xb4,0x0d,0x7a,0x36,0x60,
   0xa8,0x9e,0xca,0xf3,0x24,0x66,0xef,0x97},
  {0xf5,0xd3,0xd5,0x85,0x03,0xb9,0x69,0x9d,
   0xe7,0x85,0x89,0x5a,0x96,0xfd,0xba,0xaf}
}
Definition at line 95 of file aes.hpp.
Referenced by test().
const uint8_t AES::TV_keys static private
Initial value:
= {
  {0x2b,0x7e,0x15,0x16,0x28,0xae,0xd2,0xa6,
   0xab,0xf7,0x15,0x88,0x09,0xcf,0x4f,0x3c},
  {0x2b,0x7e,0x15,0x16,0x28,0xae,0xd2,0xa6,
   0xab,0xf7,0x15,0x88,0x09,0xcf,0x4f,0x3c}
}
Definition at line 91 of file aes.hpp.
Referenced by test().
const uint8_t AES::TV_plaintexts static private
Initial value:
= {
  {0x6b,0xc1,0xbe,0xe2,0x2e,0x40,0x9f,0x96,
   0xe9,0x3d,0x7e,0x11,0x73,0x93,0x17,0x2a},
  {0xae,0x2d,0x8a,0x57,0x1e,0x03,0xac,0x9c,
   0x9e,0xb7,0x6f,0xac,0x45,0xaf,0x8e,0x51}
}
Definition at line 93 of file aes.hpp.
Referenced by test().
The documentation for this class was generated from the following files:
includes/aes.hpp
src/aes.cpp